baseURL = "http://www.operakansas.org/"
disableKinds = ["taxonomyTerm"]
languageCode = "en-us"
title = "Opera Kansas"
[[menu.main]]
name = "Our Shows"
url = "https://operakansas.org/shows/"
weight = 2
[[menu.main]]
identifier = "education"
name = "OPERAtion EDucation"
url = "/education/"
weight = 3
[[menu.main]]
name = "ZMOC 2020"
url = "/zmoc/"
weight = 4
[[menu.main]]
identifier = "auditions"
name = "Auditions"
url = "/auditions/"
weight = 7
[params]
description = "Opera Kansas produces a series of modern and rarely performed operas throughout the state. Additionally, the opera company works with the K-12 school system to create music educational programs that fit with in the core history and literature curriculum. Opera Kansas is also committed to making opera accessible by taking performances into the community, singing in retirement homes, parks and public places in downtown Wichita."
