languageCode = "en-us"
title = "Opera Kansas"
baseURL = "http://www.operakansas.org/"

[[menu.main]]
  name = "Home"
  weight = 1
  url = "/"
[[menu.main]]
  name = "Opera Education"
  identifier = "education"
  weight = 2
  url = "/education/"
[[menu.main]]
  name = "About"
  identifier = "about"
  weight = 3
  url = "/about/"
[[menu.main]]
  name = "Auditions"
  identifier = "auditions"
  weight = 4
  url = "/auditions/"
[[menu.main]]
  name = "Donations"
  identifier = "donations"
  weight = 5
  url = "/donations/"
