---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/about
  label: About
  create: all
  match: "**/*"
- type: directory
  path: content/auditions
  label: Auditions
  create: all
  match: "**/*"
- type: directory
  path: content/donations
  label: Donations
  create: all
  match: "**/*"
- type: directory
  path: content/education
  label: Education
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.49'
